### PR TITLE
Add RuboCop

### PR DESCRIPTION
**Pull request by AlexWayfer**
*   Required Ruby version has been increased from 2.3 to 2.4.
*   Replace `require 'ferrum/*'` with `require_relative '*'` for actual version.

### CODE REVIEW

**Comment by route** [comment]
Could you please remove changes on the files and leave only rubocop integration files?

**Comment by AlexWayfer** [comment]
> Could you please remove changes on the files and leave only rubocop integration files?

I want to clarify: why, what's the point, if these changes are for resolving RuboCop offenses?

**Comment by ttilberg** [comment]
@AlexWayfer Having the setup and config of rubocop at least as a separate commit from the code implementations will allow to resolve merge conflicts, and also be more selective about some of the changes vs rules to specify for the project.

**Comment by route** [comment]
Yep @ttilberg is right, I just see some changes I don't like, so I'd rather merge setup and incrementally work with it.

**Comment by route** [comment]
Merged manually

**Comment by AlexWayfer** [comment]
> @AlexWayfer Having the setup and config of rubocop at least as a separate commit from the code implementations will allow to resolve merge conflicts, and also be more selective about some of the changes vs rules to specify for the project.

I can split it, change it for your wishes, rebase with conflicts resolving, anything else.



> Merged manually

Where?… 😰

**Comment by route** [comment]
photo_2021-03-07_07-33-08

**Comment by AlexWayfer** [comment]
OK, I just wanted a link or something like this to check, thank you. 😬

**Pull request closed without merging**
